platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'P34Utils', :git=> 'https://github.com/pilot34/P34Utils.git'
pod "AFNetworking", "~> 2.0"
pod 'JGProgressHUD'
pod "MTDates"
